CREATE TABLE IF NOT EXISTS ledger_scheduled_task (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    book_id BIGINT NOT NULL,
    task_type VARCHAR(32) NOT NULL DEFAULT 'RECURRING_TRANSACTION',
    name VARCHAR(180) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    frequency VARCHAR(16) NOT NULL DEFAULT 'MONTHLY',
    interval_value INT NOT NULL DEFAULT 1,
    start_on DATE NOT NULL,
    next_run_on DATE NOT NULL,
    end_on DATE NULL,
    max_runs INT NULL,
    run_count INT NOT NULL DEFAULT 0,
    payload_json JSON NOT NULL,
    last_run_at TIMESTAMP NULL,
    last_run_status VARCHAR(24) NULL,
    last_error VARCHAR(500) NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ledger_scheduled_task_public_id (public_id),
    KEY idx_ledger_scheduled_task_due (enabled, deleted, next_run_on),
    KEY idx_ledger_scheduled_task_book (book_id, deleted),
    CONSTRAINT fk_ledger_scheduled_task_book FOREIGN KEY (book_id) REFERENCES ledger_book(id),
    CONSTRAINT fk_ledger_scheduled_task_creator FOREIGN KEY (created_by) REFERENCES app_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ledger_scheduled_task_run (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    due_on DATE NOT NULL,
    status VARCHAR(24) NOT NULL,
    transaction_public_id CHAR(36) NULL,
    error_message VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ledger_scheduled_task_run_due (task_id, due_on),
    CONSTRAINT fk_ledger_scheduled_task_run_task FOREIGN KEY (task_id) REFERENCES ledger_scheduled_task(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
