<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.salarytracker</groupId>
        <artifactId>salary-tracker-backend</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>salary-tracker-app</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.salarytracker</groupId>
            <artifactId>salary-tracker-platform</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salarytracker</groupId>
            <artifactId>salary-tracker-identity</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salarytracker</groupId>
            <artifactId>salary-tracker-worktime</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <directory>../target</directory>
        <finalName>salary-tracker-backend</finalName>
        <sourceDirectory>../src/main/java</sourceDirectory>
        <testSourceDirectory>../src/test/java</testSourceDirectory>
        <resources>
            <resource>
                <directory>../src/main/resources</directory>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>../src/test/resources</directory>
            </testResource>
        </testResources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.salarytracker.SalaryTrackerApplication</mainClass>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals><goal>repackage</goal></goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
