export {
  ArrowLeft,
  ArrowLeftRight as Switch,
  ArrowRight,
  ArrowDownWideNarrow as SortDown,
  ArrowUpNarrowWide as SortUp,
  Banknote as Money,
  BarChart3 as DataAnalysis,
  Bike as Bicycle,
  BookOpen as Notebook,
  BookOpen as Reading,
  Briefcase,
  BriefcaseMedical as FirstAidKit,
  CalendarDays as Calendar,
  Check,
  ChevronDown as ArrowDown,
  ChevronRight,
  ChevronRight as ArrowRightSmall,
  CircleUserRound as UserFilled,
  Clock3 as Timer,
  Coins as Coin,
  Copy as CopyDocument,
  CreditCard,
  Download,
  Ellipsis as MoreFilled,
  Eye as View,
  EyeOff as Hide,
  FileText as Document,
  Film,
  FolderOpen as FolderOpened,
  Gift as Present,
  GripVertical as Rank,
  Handshake as Service,
  House,
  LayoutGrid as Grid,
  ListFilter as Filter,
  ListTodo as List,
  Lock,
  LogOut as SwitchButton,
  Luggage as Suitcase,
  MapPin as Location,
  MessageCircle as ChatDotRound,
  Minus as Remove,
  Moon,
  Package as Goods,
  PanelsTopLeft as Management,
  Pencil as EditPen,
  Plus,
  ReceiptText as Tickets,
  RefreshCw as Refresh,
  RotateCcw as RefreshLeft,
  Settings as Setting,
  SlidersHorizontal as Operation,
  ShoppingBag,
  Store as Shop,
  Sun as Sunny,
  Tags as CollectionTag,
  Ticket,
  Trash2 as Delete,
  Trash2 as DeleteFilled,
  Trophy,
  Unlock,
  Upload,
  User,
  Utensils as Food,
  WalletCards as Wallet,
  WandSparkles as MagicStick,
  Wifi as Connection,
  X as Close
} from 'lucide-vue-next'
