<template>
  <section class="ledger-page">
    <div class="page-heading ledger-heading">
      <div><div class="label">PERSONAL FINANCE / LEDGER</div><h1>账本 <span class="heading-slash">// LEDGER</span></h1><p class="muted">记录每一笔流动，月底自动对账。</p></div>
      <div class="ledger-actions"><Button size="sm" variant="ghost" @click="openAi">自然语言记账</Button><Button size="sm" variant="ghost" @click="exportCsv">导出 CSV</Button><label class="ui-button variant-ghost size-sm import-label">导入 CSV / Excel<input type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" hidden @change="importCsv" /></label><Button @click="openCreate">记一笔 <span aria-hidden="true">＋</span></Button></div>
    </div>

    <div class="ledger-status" :class="{ offline: !online }"><span class="status-dot" :class="{ online }"></span><span>{{ online ? '在线 · 自动同步' : '离线 · 已保存到本机' }}</span><span v-if="syncing" class="status-sync">正在同步…</span><button v-if="!online" class="status-link" type="button" @click="retrySync">重试</button></div>

    <div class="ledger-summary-grid">
      <Card><template #header><div class="summary-label">本月收入</div></template><div class="summary-value income">¥{{ money(summary.income) }}</div><div class="summary-meta">{{ summary.incomeCount }} 笔流入</div></Card>
      <Card><template #header><div class="summary-label">本月支出</div></template><div class="summary-value expense">¥{{ money(summary.expense) }}</div><div class="summary-meta">{{ summary.expenseCount }} 笔流出</div></Card>
      <Card><template #header><div class="summary-label">本月结余</div></template><div class="summary-value" :class="summary.net >= 0 ? 'income' : 'expense'">¥{{ money(summary.net) }}</div><div class="summary-meta">收入 − 支出</div></Card>
      <Card><template #header><div class="summary-label">总资产</div></template><div class="summary-value">¥{{ money(totalBalance) }}</div><div class="summary-meta">{{ accounts.length }} 个账户</div></Card>
    </div>

    <div class="ledger-layout">
      <div class="ledger-main-column">
        <Card class="ledger-list-card"><template #header><div class="card-header-row"><div><div class="card-kicker">TRANSACTIONS</div><h2>最近交易</h2></div><div class="filter-tabs"><button v-for="tab in tabs" :key="tab.key" type="button" :class="{ active: filter === tab.key }" @click="filter = tab.key">{{ tab.label }}</button></div></div></template>
          <div v-if="filteredTransactions.length" class="transaction-table-wrap"><Table><thead><tr><th>日期</th><th>描述</th><th>分类</th><th>账户</th><th class="amount-col">金额</th><th></th></tr></thead><tbody><tr v-for="item in filteredTransactions" :key="item.id" @dblclick="editTransaction(item)"><td class="num date-cell">{{ formatDate(item.occurredOn) }}</td><td><div class="transaction-payee">{{ item.payee || item.note || '未命名交易' }}</div><div v-if="item.note && item.payee" class="transaction-note">{{ item.note }}</div></td><td><span class="category-dot" :style="{ background: categoryColor(item.categoryId) }"></span>{{ item.categoryName || '未分类' }}</td><td>{{ item.accountName }}</td><td class="amount-col num" :class="item.kind === 'INCOME' ? 'income' : 'expense'">{{ item.kind === 'INCOME' ? '+' : '−' }}¥{{ money(item.amount) }}</td><td class="action-cell"><button type="button" class="row-action" aria-label="编辑交易" @click="editTransaction(item)">编辑</button><button type="button" class="row-action danger-action" aria-label="删除交易" @click="removeTransaction(item)">删</button></td></tr></tbody></Table></div>
          <div v-else class="ledger-empty"><div class="empty-mark">∅</div><strong>还没有交易</strong><span>记下第一笔，让账本开始运转。</span><Button size="sm" @click="openCreate">记一笔</Button></div>
          <div class="list-footer"><span>显示 {{ filteredTransactions.length }} / {{ transactions.length }} 笔</span><button type="button" class="text-button" @click="loadData">刷新</button></div>
        </Card>

        <Card class="ledger-chart-card"><template #header><div class="card-header-row"><div><div class="card-kicker">CASH FLOW</div><h2>收支趋势</h2></div><div class="chart-range">{{ monthLabel }}</div></div></template><div ref="trendChartRef" class="ledger-chart" aria-label="收支趋势图"></div></Card>
      </div>

      <aside class="ledger-side-column">
        <Card class="account-card"><template #header><div class="card-header-row"><div><div class="card-kicker">ACCOUNTS</div><h2>账户</h2></div><button type="button" class="text-button" @click="openAccountManager">管理</button></div></template><div class="account-list"><button v-for="account in accounts" :key="account.id" class="account-row" type="button" @click="openAccountManager(account)"><span class="account-icon">{{ accountIcon(account.accountType) }}</span><span class="account-info"><strong>{{ account.name }}</strong><small>{{ account.accountType }}</small></span><span class="account-balance num">¥{{ money(account.balance) }}</span></button><div v-if="!accounts.length" class="side-empty">添加一个账户开始记账。</div></div><Button class="account-add" variant="ghost" size="sm" @click="openAccountManager()">＋ 添加账户</Button></Card>
        <Card class="category-card"><template #header><div class="card-header-row"><div><div class="card-kicker">THIS MONTH</div><h2>分类占比</h2></div><span class="summary-meta">支出</span></div></template><div ref="categoryChartRef" class="category-chart" aria-label="分类占比图"></div><div class="category-legend"><div v-for="item in categoryBreakdown.slice(0, 4)" :key="item.category" class="legend-row"><span class="legend-dot" :style="{ background: item.color }"></span><span>{{ item.category }}</span><span class="num">¥{{ money(item.amount) }}</span></div></div></Card>
        <Card class="budget-card"><template #header><div class="card-header-row"><div><div class="card-kicker">BUDGET</div><h2>预算执行</h2></div><button type="button" class="text-button" @click="openBudgetManager">设置</button></div></template><div v-if="budgets.length" class="budget-list"><div v-for="budget in budgets" :key="budget.id" class="budget-row"><div class="budget-row-head"><span>{{ budget.category }}</span><span class="num">¥{{ money(budget.spent) }} / ¥{{ money(budget.budget) }}</span></div><div class="budget-track"><span :class="{ over: Number(budget.spent) > Number(budget.budget) }" :style="{ width: `${Math.min(100, Number(budget.spent) / Math.max(1, Number(budget.budget)) * 100)}%` }"></span></div></div></div><div v-else class="side-empty">在预算设置中添加本月分类预算。</div></Card>
        <Card class="recurring-card"><template #header><div class="card-header-row"><div><div class="card-kicker">RECURRING</div><h2>周期账单</h2></div><div class="recurring-actions"><button type="button" class="text-button" @click="openRecurring">新增</button><button type="button" class="text-button" @click="runRecurring">立即检查</button></div></div></template><div v-if="recurringBills.length" class="recurring-list"><div v-for="bill in recurringBills.slice(0, 4)" :key="bill.id" class="recurring-row"><div><strong>{{ bill.title }}</strong><small>{{ bill.frequency === 'MONTHLY' ? '每月' : bill.frequency === 'WEEKLY' ? '每周' : '每年' }} · {{ bill.nextDue }}</small></div><span class="num expense">−¥{{ money(bill.amount) }}</span></div></div><div v-else class="side-empty">还没有周期账单。到期后自动生成交易。</div></Card>
      </aside>
    </div>

    <Sheet v-model:open="editorOpen" :title="editing ? '编辑交易' : '记一笔'"><form class="ledger-form" @submit.prevent="saveTransaction"><div class="form-kind"><button type="button" :class="{ active: form.kind === 'EXPENSE' }" @click="form.kind = 'EXPENSE'">支出</button><button type="button" :class="{ active: form.kind === 'INCOME' }" @click="form.kind = 'INCOME'">收入</button></div><label>金额 <div class="amount-input"><span>¥</span><input v-model="form.amount" class="ui-input" type="number" step="0.01" min="0.01" required placeholder="0.00" /></div></label><label>日期<input v-model="form.occurredOn" class="ui-input" type="date" required /></label><label>账户<select v-model="form.accountId" class="ui-select" required><option value="" disabled>选择账户</option><option v-for="account in accounts" :key="account.id" :value="String(account.id)">{{ account.name }}</option></select></label><label>分类<select v-model="form.categoryId" class="ui-select"><option value="">未分类</option><option v-for="category in categoriesForKind" :key="category.id" :value="String(category.id)">{{ category.name }}</option></select></label><label>商户 / 描述<input v-model="form.payee" class="ui-input" placeholder="例如：便利店、工资" /></label><label>备注<textarea v-model="form.note" class="ui-textarea" rows="3" placeholder="可选"></textarea></label><div class="form-footer"><Button type="button" variant="ghost" @click="editorOpen = false">取消</Button><Button type="submit">{{ editing ? '保存修改' : '保存交易' }}</Button></div></form></Sheet>

    <Drawer v-model:open="managerOpen" title="账户与分类"><div class="manager-tabs"><button type="button" :class="{ active: managerTab === 'accounts' }" @click="managerTab = 'accounts'">账户</button><button type="button" :class="{ active: managerTab === 'categories' }" @click="managerTab = 'categories'">分类</button></div><div v-if="managerTab === 'accounts'" class="manager-content"><div v-for="account in accounts" :key="account.id" class="manager-row"><div><strong>{{ account.name }}</strong><small>{{ account.accountType }} · ¥{{ money(account.balance) }}</small></div><button type="button" class="row-action" @click="removeAccount(account)">删除</button></div><form class="mini-form" @submit.prevent="saveAccount"><input v-model="accountForm.name" class="ui-input" placeholder="账户名称" required /><select v-model="accountForm.accountType" class="ui-select"><option value="cash">现金</option><option value="bank">银行卡</option><option value="card">信用卡</option><option value="wallet">电子钱包</option></select><input v-model="accountForm.openingBalance" class="ui-input" type="number" step="0.01" placeholder="期初余额" /><Button size="sm" type="submit">添加账户</Button></form></div><div v-else class="manager-content"><div v-for="category in categories" :key="category.id" class="manager-row"><div><span class="category-dot" :style="{ background: category.color }"></span><strong>{{ category.name }}</strong><small>{{ category.kind === 'INCOME' ? '收入' : '支出' }}</small></div><button type="button" class="row-action" @click="removeCategory(category)">删除</button></div><form class="mini-form" @submit.prevent="saveCategory"><input v-model="categoryForm.name" class="ui-input" placeholder="分类名称" required /><select v-model="categoryForm.kind" class="ui-select"><option value="EXPENSE">支出</option><option value="INCOME">收入</option></select><Button size="sm" type="submit">添加分类</Button></form></div></Drawer>

    <Sheet v-model:open="aiOpen" title="自然语言记账"><div class="ai-intro">说说刚刚发生的交易，助手会整理成可确认的记录。</div><textarea v-model="aiText" class="ui-textarea ai-textarea" rows="4" placeholder="例如：今天午饭花了 32 元"></textarea><Button class="ai-preview-button" :disabled="aiLoading" @click="getAiPreview">{{ aiLoading ? '识别中…' : '识别交易' }}</Button><div v-if="aiPreview" class="ai-preview"><div class="card-kicker">PREVIEW / 需要确认</div><div class="ai-preview-amount" :class="aiPreview.kind === 'INCOME' ? 'income' : 'expense'">{{ aiPreview.kind === 'INCOME' ? '+' : '−' }}¥{{ money(aiPreview.amount) }}</div><div class="ai-preview-meta">{{ aiPreview.category }} · {{ aiPreview.occurredOn }}</div><p>{{ aiPreview.note }}</p><div class="form-footer"><Button variant="ghost" @click="aiPreview = null">重新输入</Button><Button @click="confirmAi">确认记账</Button></div></div></Sheet>
    <Sheet v-model:open="recurringOpen" title="新增周期账单"><form class="ledger-form" @submit.prevent="saveRecurring"><label>名称<input v-model="recurringForm.title" class="ui-input" required placeholder="例如：房租、音乐会员" /></label><label>金额<input v-model="recurringForm.amount" class="ui-input" type="number" min="0.01" step="0.01" required /></label><label>账户<select v-model="recurringForm.accountId" class="ui-select" required><option value="" disabled>选择账户</option><option v-for="account in accounts" :key="account.id" :value="String(account.id)">{{ account.name }}</option></select></label><label>分类<select v-model="recurringForm.categoryId" class="ui-select"><option value="">未分类</option><option v-for="category in categories.filter(item => item.kind === 'EXPENSE')" :key="category.id" :value="String(category.id)">{{ category.name }}</option></select></label><label>频率<select v-model="recurringForm.frequency" class="ui-select"><option value="MONTHLY">每月</option><option value="WEEKLY">每周</option><option value="YEARLY">每年</option></select></label><label>下次到期<input v-model="recurringForm.nextDue" class="ui-input" type="date" required /></label><div class="form-footer"><Button type="button" variant="ghost" @click="recurringOpen = false">取消</Button><Button type="submit">保存周期账单</Button></div></form></Sheet>
  </section>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import * as echarts from 'echarts'
import { ElMessage } from 'element-plus'
import Card from '../components/ui/Card.vue'
import Button from '../components/ui/Button.vue'
import Table from '../components/ui/Table.vue'
import Sheet from '../components/ui/Sheet.vue'
import Drawer from '../components/ui/Drawer.vue'
import { createLedgerSyncEngine } from '../../packages/sync-engine/src/index.js'
import { apiCreateLedgerAccount, apiCreateLedgerCategory, apiCreateLedgerTransaction, apiUpdateLedgerTransaction, apiDeleteLedgerAccount, apiDeleteLedgerCategory, apiDeleteLedgerTransaction, apiGetLedgerReports, apiLedgerAiConfirm, apiLedgerAiPreview, apiListLedgerAccounts, apiListLedgerCategories, apiListLedgerTransactions, apiPushLedgerSync, apiPullLedgerSync, apiListRecurringBills, apiImportLedgerCsv, apiImportLedgerExcel } from '../api'

const accounts = ref([]); const categories = ref([]); const transactions = ref([]); const reports = ref({}); const budgets = ref([]); const recurringBills = ref([])
const filter = ref('all'); const online = ref(navigator.onLine); const syncing = ref(false)
const editorOpen = ref(false); const editing = ref(null); const managerOpen = ref(false); const managerTab = ref('accounts'); const aiOpen = ref(false); const aiText = ref(''); const aiPreview = ref(null); const aiLoading = ref(false); const recurringOpen = ref(false)
const form = reactive({ kind: 'EXPENSE', amount: '', occurredOn: new Date().toISOString().slice(0, 10), accountId: '', categoryId: '', payee: '', note: '' })
const accountForm = reactive({ name: '', accountType: 'cash', openingBalance: '' }); const categoryForm = reactive({ name: '', kind: 'EXPENSE' })
const recurringForm = reactive({ title: '', amount: '', accountId: '', categoryId: '', frequency: 'MONTHLY', nextDue: new Date().toISOString().slice(0, 10) })
const trendChartRef = ref(null); const categoryChartRef = ref(null); let trendChart; let categoryChart
const tabs = [{ key: 'all', label: '全部' }, { key: 'EXPENSE', label: '支出' }, { key: 'INCOME', label: '收入' }]
const monthKey = new Date().toISOString().slice(0, 7); const monthLabel = `${monthKey.slice(0, 4)} 年 ${Number(monthKey.slice(5))} 月`

const filteredTransactions = computed(() => transactions.value.filter(item => filter.value === 'all' || item.kind === filter.value))
const categoriesForKind = computed(() => categories.value.filter(item => item.kind === form.kind))
const totalBalance = computed(() => accounts.value.reduce((sum, item) => sum + Number(item.balance || 0), 0))
const summary = computed(() => { const monthly = transactions.value.filter(item => String(item.occurredOn).slice(0, 7) === monthKey); const income = monthly.filter(item => item.kind === 'INCOME'); const expense = monthly.filter(item => item.kind === 'EXPENSE'); const incomeTotal = income.reduce((sum, item) => sum + Number(item.amount || 0), 0); const expenseTotal = expense.reduce((sum, item) => sum + Number(item.amount || 0), 0); return { income: incomeTotal, expense: expenseTotal, net: incomeTotal - expenseTotal, incomeCount: income.length, expenseCount: expense.length } })
const categoryBreakdown = computed(() => { const map = new Map(); for (const item of transactions.value.filter(item => item.kind === 'EXPENSE' && String(item.occurredOn).slice(0, 7) === monthKey)) { const key = item.categoryName || '未分类'; map.set(key, (map.get(key) || 0) + Number(item.amount || 0)) } const colors = ['#0f5132', '#5b7c99', '#b08b57', '#9a667d', '#6e7781']; return [...map.entries()].sort((a, b) => b[1] - a[1]).map(([category, amount], index) => ({ category, amount, color: colors[index % colors.length] })) })

const engine = createLedgerSyncEngine({ push: apiPushLedgerSync, pull: apiPullLedgerSync })
function money(value) { return Number(value || 0).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) }
function formatDate(value) { return String(value || '').replaceAll('-', '/') }
function categoryColor(id) { return categories.value.find(item => String(item.id) === String(id))?.color || 'var(--line2)' }
function accountIcon(type) { return ({ cash: '¥', bank: '▣', card: '▤', wallet: '◒', other: '·' })[type] || '·' }

async function loadData() { try { const [a, c, t, r, recurring] = await Promise.all([apiListLedgerAccounts(), apiListLedgerCategories(), apiListLedgerTransactions({ limit: 200 }), apiGetLedgerReports({ from: `${monthKey}-01`, to: new Date().toISOString().slice(0, 10) }), apiListRecurringBills()]); accounts.value = a || []; categories.value = c || []; transactions.value = t || []; reports.value = r || {}; budgets.value = r?.budgets || []; recurringBills.value = recurring || []; await cacheData(); await drawCharts() } catch (error) { online.value = false; await loadCachedData() } }
async function cacheData() { await Promise.all(accounts.value.map(item => engine.put('account', item, { opId: `server-account-${item.id}-${item.revision}`, recordOp: false }))); await Promise.all(categories.value.map(item => engine.put('category', item, { opId: `server-category-${item.id}-${item.revision}`, recordOp: false }))); await Promise.all(transactions.value.map(item => engine.put('transaction', item, { opId: `server-transaction-${item.id}-${item.revision}`, recordOp: false }))) }
async function loadCachedData() { accounts.value = await engine.list('account'); categories.value = await engine.list('category'); transactions.value = await engine.list('transaction') }
async function syncNow() { if (!navigator.onLine) return; syncing.value = true; try { const result = await engine.sync(); online.value = true; if (result.pushed || result.pulled) await loadData() } catch (error) { online.value = false } finally { syncing.value = false } }
function retrySync() { loadData() }
function onOnline() { online.value = true; syncNow() }
function onOffline() { online.value = false }
function openCreate() { editing.value = null; Object.assign(form, { kind: 'EXPENSE', amount: '', occurredOn: new Date().toISOString().slice(0, 10), accountId: accounts.value[0] ? String(accounts.value[0].id) : '', categoryId: '', payee: '', note: '' }); editorOpen.value = true }
function editTransaction(item) { editing.value = item; Object.assign(form, { kind: item.kind, amount: item.amount, occurredOn: item.occurredOn, accountId: String(item.accountId), categoryId: item.categoryId ? String(item.categoryId) : '', payee: item.payee || '', note: item.note || '' }); editorOpen.value = true }
async function saveTransaction() { const payload = { ...form, amount: Number(form.amount), accountId: Number(form.accountId), categoryId: form.categoryId ? Number(form.categoryId) : null, occurredOn: form.occurredOn, clientOpId: `web-${Date.now()}-${Math.random().toString(16).slice(2)}` }; try { if (editing.value) { const response = online.value ? await apiUpdateLedgerTransaction(editing.value.id, payload, editing.value.revision) : { ...editing.value, ...payload, revision: Number(editing.value.revision || 0) + 1 }; await engine.put('transaction', response, { opId: payload.clientOpId }) } else { const response = online.value ? await apiCreateLedgerTransaction(payload, payload.clientOpId) : payload; const local = { ...response, ...payload, id: response?.id || payload.clientOpId, revision: response?.revision || 1, accountName: accounts.value.find(item => String(item.id) === String(payload.accountId))?.name || '', categoryName: categories.value.find(item => String(item.id) === String(payload.categoryId))?.name || '' }; await engine.put('transaction', local, { opId: payload.clientOpId }) } editorOpen.value = false; ElMessage.success(online.value ? '交易已保存并同步' : '已保存到本机，联网后自动同步'); await loadData(); await syncNow() } catch (error) { ElMessage.error(error.response?.data?.detail || '保存失败') } }
async function removeTransaction(item) { if (!window.confirm('删除后交易仍保留历史记录，确定删除？')) return; try { await apiDeleteLedgerTransaction(item.id, item.revision); await engine.remove('transaction', item.id); await loadData() } catch (error) { ElMessage.error('删除失败') } }
function openAccountManager(account) { managerTab.value = 'accounts'; managerOpen.value = true; if (account) ElMessage.info(`${account.name} 当前余额 ¥${money(account.balance)}`) }
async function saveAccount() { try { const result = await apiCreateLedgerAccount({ ...accountForm, openingBalance: Number(accountForm.openingBalance || 0) }); await engine.put('account', result, { opId: `account-${result.id}` }); Object.assign(accountForm, { name: '', accountType: 'cash', openingBalance: '' }); await loadData() } catch (error) { ElMessage.error('账户保存失败') } }
async function removeAccount(account) { if (!window.confirm(`删除账户“${account.name}”？`)) return; try { await apiDeleteLedgerAccount(account.id, account.revision); await loadData() } catch (error) { ElMessage.error('账户删除失败') } }
async function saveCategory() { try { const result = await apiCreateLedgerCategory(categoryForm); await engine.put('category', result, { opId: `category-${result.id}` }); Object.assign(categoryForm, { name: '', kind: 'EXPENSE' }); await loadData() } catch (error) { ElMessage.error('分类保存失败') } }
async function removeCategory(category) { if (!window.confirm(`删除分类“${category.name}”？`)) return; try { await apiDeleteLedgerCategory(category.id, category.revision); await loadData() } catch (error) { ElMessage.error('分类删除失败') } }
function openBudgetManager() { ElMessage.info('预算设置 API 将在下一小版本开放；当前报表已支持预算执行数据。') }
function openRecurring() { Object.assign(recurringForm, { title: '', amount: '', accountId: accounts.value[0] ? String(accounts.value[0].id) : '', categoryId: '', frequency: 'MONTHLY', nextDue: new Date().toISOString().slice(0, 10) }); recurringOpen.value = true }
async function saveRecurring() { try { const { apiCreateRecurringBill } = await import('../api'); await apiCreateRecurringBill({ ...recurringForm, amount: Number(recurringForm.amount), accountId: Number(recurringForm.accountId), categoryId: recurringForm.categoryId ? Number(recurringForm.categoryId) : null }); recurringOpen.value = false; await loadData(); ElMessage.success('周期账单已保存') } catch (error) { ElMessage.error(error.response?.data?.detail || '周期账单保存失败') } }
async function runRecurring() { try { const { apiRunRecurringBills } = await import('../api'); const result = await apiRunRecurringBills(); ElMessage.success(`已检查周期账单，生成 ${result.generated || 0} 笔交易`); await loadData() } catch (error) { ElMessage.error('周期账单检查失败') } }
function openAi() { aiText.value = ''; aiPreview.value = null; aiOpen.value = true }
async function getAiPreview() { if (!aiText.value.trim()) return; aiLoading.value = true; try { aiPreview.value = await apiLedgerAiPreview(aiText.value) } catch (error) { ElMessage.error(error.response?.data?.detail || '暂时无法识别') } finally { aiLoading.value = false } }
async function confirmAi() { try { const result = await apiLedgerAiConfirm(aiPreview.value); aiOpen.value = false; await engine.put('transaction', result, { opId: `ai-${result.id}` }); await loadData(); ElMessage.success('AI 记账完成') } catch (error) { ElMessage.error('记账失败') } }
async function importCsv(event) { const file = event.target.files?.[0]; if (!file) return; try { if (online.value && /\.xlsx?$/i.test(file.name)) { const imported = await apiImportLedgerExcel(file); ElMessage.success(`已导入 ${imported?.length || 0} 笔交易`) } else if (online.value) { const imported = await apiImportLedgerCsv(file); ElMessage.success(`已导入 ${imported?.length || 0} 笔交易`) } else { const text = await file.text(); const lines = text.split(/\r?\n/).filter(Boolean); const headers = (lines.shift() || '').split(',').map(item => item.trim()); let imported = 0; for (const line of lines) { const cells = line.split(',').map(item => item.trim().replace(/^\"|\"$/g, '')); const row = Object.fromEntries(headers.map((header, index) => [header, cells[index] || ''])); const account = accounts.value.find(item => item.name === (row.账户 || row.account)) || accounts.value[0]; if (!account || !(row.金额 || row.amount)) continue; const category = categories.value.find(item => item.name === (row.分类 || row.category)); const payload = { accountId: account.id, categoryId: category?.id || null, kind: /收入|income/i.test(row.类型 || row.kind) ? 'INCOME' : 'EXPENSE', amount: Math.abs(Number((row.金额 || row.amount).replace(/,/g, ''))), occurredOn: (row.日期 || row.date).replaceAll('/', '-'), payee: row.商户 || row.payee || '', note: row.备注 || row.note || '', source: 'import', clientOpId: `csv-${Date.now()}-${imported}` }; await engine.put('transaction', { ...payload, id: payload.clientOpId, revision: 1 }, { opId: payload.clientOpId }); imported++ } ElMessage.success(`离线导入 ${imported} 笔交易，联网后自动同步`) } await loadData() } catch (error) { ElMessage.error(error.response?.data?.detail || '导入失败') } finally { event.target.value = '' } }
async function exportCsv() { const rows = transactions.value; const csv = ['日期,类型,金额,账户,分类,商户,备注', ...rows.map(item => [item.occurredOn, item.kind, item.amount, item.accountName, item.categoryName || '', item.payee || '', item.note || ''].map(value => `"${String(value).replaceAll('"', '""')}"`).join(','))].join('\n'); const blob = new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `ledger-${monthKey}.csv`; link.click(); URL.revokeObjectURL(url) }

async function drawCharts() { await nextTick(); const styles = getComputedStyle(document.documentElement); const text = styles.getPropertyValue('--ink2').trim() || '#49505c'; const line = styles.getPropertyValue('--line').trim() || '#e2ded4'; const accent = styles.getPropertyValue('--accent').trim() || '#0f5132'; const trend = reports.value.trend || []; if (trendChartRef.value) { trendChart?.dispose(); trendChart = echarts.init(trendChartRef.value); trendChart.setOption({ animationDuration: 350, grid: { left: 12, right: 12, top: 18, bottom: 24, containLabel: true }, tooltip: { trigger: 'axis' }, legend: { show: false }, xAxis: { type: 'category', data: trend.map(item => String(item.date).slice(5)), axisLine: { lineStyle: { color: line } }, axisLabel: { color: text, fontSize: 10 } }, yAxis: { type: 'value', axisLabel: { color: text, fontSize: 10 }, splitLine: { lineStyle: { color: line, type: 'dashed' } } }, series: [{ name: '收入', type: 'line', smooth: true, symbol: 'none', data: trend.map(item => Number(item.income)), lineStyle: { color: accent, width: 2 }, areaStyle: { color: `${accent}18` } }, { name: '支出', type: 'line', smooth: true, symbol: 'none', data: trend.map(item => Number(item.expense)), lineStyle: { color: '#b54708', width: 2 } }] }) } if (categoryChartRef.value) { categoryChart?.dispose(); categoryChart = echarts.init(categoryChartRef.value); categoryChart.setOption({ tooltip: { trigger: 'item', formatter: '{b}: ¥{c} ({d}%)' }, series: [{ type: 'pie', radius: ['58%', '78%'], center: ['50%', '50%'], avoidLabelOverlap: true, label: { show: false }, data: categoryBreakdown.value.length ? categoryBreakdown.value.map(item => ({ name: item.category, value: item.amount, itemStyle: { color: item.color } })) : [{ name: '暂无支出', value: 1, itemStyle: { color: line } }] }] }) } }
function resizeCharts() { trendChart?.resize(); categoryChart?.resize() }
watch(() => document.documentElement.classList.contains('dark'), drawCharts)
onMounted(() => { window.addEventListener('online', onOnline); window.addEventListener('offline', onOffline); loadData(); if (!online.value) loadCachedData(); window.addEventListener('resize', resizeCharts) })
onBeforeUnmount(() => { window.removeEventListener('online', onOnline); window.removeEventListener('offline', onOffline); window.removeEventListener('resize', resizeCharts); trendChart?.dispose(); categoryChart?.dispose() })
</script>

<style scoped>
.ledger-heading { margin-bottom: 18px }
.heading-slash { color: var(--muted); font: 600 12px ui-sans-serif,system-ui; letter-spacing: .12em }
.ledger-heading .muted { margin: 8px 0 0 }
.ledger-actions { display: flex; align-items: center; gap: 8px; flex-wrap: wrap }
.import-label { cursor: pointer }
.ledger-status { display: flex; align-items: center; gap: 8px; margin-bottom: 20px; color: var(--up); font-size: 12px }
.ledger-status.offline { color: var(--warn) }
.status-dot { width: 7px; height: 7px; border-radius: 50%; background: var(--warn) }
.status-dot.online { background: var(--up); box-shadow: 0 0 0 3px color-mix(in srgb, var(--up) 14%, transparent) }
.status-sync { color: var(--muted); margin-left: 4px }
.status-link { border: 0; background: transparent; color: inherit; font: inherit; text-decoration: underline; margin-left: auto }
.ledger-summary-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; margin-bottom: 20px }
.ledger-summary-grid :deep(.card) { min-height: 130px }
.summary-label, .summary-meta { color: var(--muted); font-size: 11px }
.summary-value { font: 700 clamp(25px, 3vw, 34px)/1 Georgia,serif; margin: 5px 0 10px; color: var(--ink) }
.summary-value.income { color: var(--up) }.summary-value.expense { color: var(--down) }
.ledger-layout { display: grid; grid-template-columns: minmax(0, 1fr) 320px; gap: 20px; align-items: stretch }
.ledger-main-column { display: grid; grid-template-rows: auto minmax(270px, 1fr); gap: 20px; min-width: 0 }
.ledger-side-column { display: flex; flex-direction: column; gap: 20px; min-width: 0; height: 100% }
.ledger-chart-card { height: 100%; display: flex; flex-direction: column }
.ledger-chart-card > div:last-child { display: flex; flex: 1; min-height: 270px }
.ledger-chart { width: 100%; height: auto; min-height: 270px; flex: 1 }
.recurring-card { margin-top: auto }
.card-header-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px }
.card-kicker { color: var(--muted); font-size: 10px; letter-spacing: .16em; font-weight: 600 }
.card-header-row h2 { margin: 4px 0 0; font: 700 21px/1.2 Georgia,serif }
.filter-tabs { display: flex; gap: 2px; border: 1px solid var(--line2); padding: 2px; border-radius: 3px }
.filter-tabs button, .manager-tabs button { border: 0; background: transparent; color: var(--muted); font-size: 11px; padding: 6px 10px; cursor: pointer }.filter-tabs button.active, .manager-tabs button.active { color: var(--ink); background: var(--accent-soft); font-weight: 600 }
.amount-col { text-align: right !important }.date-cell { color: var(--ink2); white-space: nowrap }.transaction-payee { color: var(--ink); font-weight: 600 }.transaction-note { color: var(--muted); font-size: 11px; margin-top: 2px; max-width: 180px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap }.category-dot, .legend-dot { display: inline-block; width: 7px; height: 7px; border-radius: 50%; margin-right: 7px; vertical-align: middle }.row-action { border: 0; background: transparent; color: var(--muted); font-size: 15px; padding: 7px; cursor: pointer }.row-action:hover { color: var(--ink) }.list-footer { display: flex; justify-content: space-between; color: var(--muted); font-size: 11px; margin-top: 14px }.text-button { border: 0; background: transparent; color: var(--accent); font: 600 12px inherit; cursor: pointer; padding: 0 }.ledger-empty { min-height: 240px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 7px; color: var(--muted); text-align: center }.ledger-empty strong { color: var(--ink); font-size: 14px }.empty-mark { font: 32px Georgia,serif; color: var(--line2); margin-bottom: 4px }.ledger-empty .ui-button { margin-top: 8px }.chart-range { color: var(--muted); font-size: 11px }.account-list { display: flex; flex-direction: column }.account-row { width: 100%; display: flex; align-items: center; gap: 10px; text-align: left; background: transparent; border: 0; border-bottom: 1px solid var(--line); padding: 11px 0; color: var(--ink); cursor: pointer }.account-row:last-child { border-bottom: 0 }.account-icon { display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 28px; border: 1px solid var(--line2); border-radius: 50%; color: var(--accent); font-size: 13px }.account-info { display: flex; flex-direction: column; flex: 1 }.account-info strong { font-size: 13px }.account-info small { color: var(--muted); font-size: 10px; margin-top: 2px }.account-balance { color: var(--ink2); font-size: 12px }.account-add { width: 100%; margin-top: 12px }.side-empty { color: var(--muted); font-size: 12px; padding: 12px 0 }.category-chart { height: 150px }.category-legend { border-top: 1px solid var(--line); margin-top: 8px; padding-top: 8px }.legend-row { display: flex; align-items: center; gap: 4px; font-size: 11px; color: var(--ink2); padding: 4px 0 }.legend-row span:nth-child(2) { flex: 1 }.budget-list { display: flex; flex-direction: column; gap: 14px }.budget-row-head { display: flex; justify-content: space-between; gap: 8px; font-size: 11px; color: var(--ink2); margin-bottom: 6px }.budget-track { height: 5px; border-radius: 4px; background: var(--accent-soft); overflow: hidden }.budget-track span { display: block; height: 100%; background: var(--accent); border-radius: 4px }.budget-track span.over { background: var(--down) }
.ledger-form, .manager-content { display: flex; flex-direction: column; gap: 15px }.ledger-form label { display: flex; flex-direction: column; gap: 6px; color: var(--ink2); font-size: 12px; font-weight: 600 }.form-kind { display: grid; grid-template-columns: 1fr 1fr; gap: 4px; background: var(--paper); padding: 4px; border: 1px solid var(--line); border-radius: 4px }.form-kind button { border: 0; background: transparent; color: var(--muted); padding: 10px; font-weight: 600; cursor: pointer }.form-kind button.active { color: var(--ink); background: var(--card); box-shadow: 0 1px 3px rgba(20,23,28,.12) }.amount-input { position: relative }.amount-input > span { position: absolute; left: 12px; top: 8px; color: var(--muted); font: 700 20px Georgia,serif }.amount-input .ui-input { padding-left: 32px; font-size: 22px; font-weight: 700; height: 46px }.form-footer { display: flex; justify-content: flex-end; gap: 8px; padding-top: 6px }.manager-tabs { display: flex; gap: 4px; border-bottom: 1px solid var(--line); padding-bottom: 8px }.manager-row { display: flex; justify-content: space-between; align-items: center; padding: 12px 0; border-bottom: 1px solid var(--line) }.manager-row strong { display: block; color: var(--ink); font-size: 13px }.manager-row small { display: block; color: var(--muted); font-size: 11px; margin-top: 3px }.mini-form { display: flex; flex-direction: column; gap: 8px; padding-top: 10px }.ai-intro { color: var(--ink2); font-size: 13px; line-height: 1.7; margin-bottom: 10px }.ai-textarea { min-height: 110px }.ai-preview-button { width: 100%; margin-top: 10px }.ai-preview { margin-top: 22px; border-top: 1px solid var(--line); padding-top: 20px }.ai-preview-amount { font: 700 38px/1 Georgia,serif; margin: 10px 0 5px }.ai-preview-meta { color: var(--muted); font-size: 12px }.ai-preview p { color: var(--ink2); font-size: 13px; margin: 16px 0 }.income { color: var(--up) }.expense { color: var(--down) }
.recurring-list { display: flex; flex-direction: column }.recurring-row { display: flex; justify-content: space-between; align-items: center; gap: 8px; padding: 10px 0; border-bottom: 1px solid var(--line) }.recurring-row:last-child { border-bottom: 0 }.recurring-row strong { display: block; color: var(--ink); font-size: 12px }.recurring-row small { display: block; color: var(--muted); font-size: 10px; margin-top: 3px }
@media (max-width: 1023px) { .ledger-layout { grid-template-columns: 1fr; align-items: start }.ledger-main-column { display: flex; flex-direction: column }.ledger-side-column { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); height: auto }.ledger-chart-card { height: auto }.recurring-card { margin-top: 0 }.budget-card { grid-column: span 2 } }
@media (max-width: 767px) { .ledger-summary-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px }.ledger-summary-grid :deep(.card) { min-height: 112px; padding: 15px }.summary-value { font-size: 25px }.ledger-actions { width: 100% }.ledger-actions .ui-button { flex: 1 }.ledger-actions .import-label { flex: 1 }.ledger-side-column { display: flex }.budget-card { grid-column: auto }.ledger-list-card :deep(.card-header-row) { flex-direction: column; gap: 12px }.filter-tabs { align-self: stretch }.filter-tabs button { flex: 1 }.transaction-table-wrap { margin: 0 -15px }.ledger-list-card :deep(.ui-table) { min-width: 560px }.ledger-list-card :deep(.ui-table th:nth-child(3)), .ledger-list-card :deep(.ui-table td:nth-child(3)), .ledger-list-card :deep(.ui-table th:nth-child(4)), .ledger-list-card :deep(.ui-table td:nth-child(4)) { display: none }.ledger-chart { height: 220px } }
</style>
