<template>
  <main class="efficiency-page focus-page">
    <header class="efficiency-head"><div><p class="label">TASKS / FOCUS</p><h1>专注</h1><p>主动专注时长独立于工时口径。</p></div><Button variant="ghost" @click="settingsOpen = !settingsOpen"><Settings2 :size="16" />参数</Button></header>
    <p v-if="focus.error" class="efficiency-error" role="alert">{{ focus.error }}</p>
    <section class="focus-stage" :class="{ running: focus.current }"><p>{{ focus.current ? '进行中' : requestedDate ? `${requestedDate} 补记` : '准备开始' }}</p><strong>{{ focus.current ? focus.remainingLabel : `${focus.settings?.focusMinutes || 25}:00` }}</strong><span>{{ focus.current?.taskTitle || '选择一个任务，开始一段专注' }}</span><div class="focus-actions"><Button v-if="!focus.current" :disabled="focus.loading" @click="focus.start({ taskId: selectedTask || undefined, requestedDate: requestedDate || undefined })"><Timer :size="17" />{{ requestedDate ? '添加专注记录' : '开始专注' }}</Button><template v-else><Button variant="danger" :disabled="focus.loading" @click="focus.abort"><Square :size="15" />放弃</Button><Button :disabled="focus.loading" @click="focus.complete"><Check :size="16" />完成</Button></template></div></section>
    <section class="focus-summary"><div><b>{{ focus.stats?.todayCount || 0 }}</b><span>今日番茄</span></div><div><b>{{ focus.stats?.todayMinutes || 0 }} 分钟</b><span>今日专注</span></div><div><b>{{ focus.stats?.weekMinutes || 0 }} 分钟</b><span>本周专注</span></div><label v-if="tasksStore.openTasks.length">关联任务<select v-model="selectedTask"><option value="">不关联任务</option><option v-for="task in tasksStore.openTasks" :key="task.publicId" :value="task.publicId">{{ task.title }}</option></select></label></section>
    <section v-if="settingsOpen" class="efficiency-panel"><h2>番茄参数</h2><div class="form-grid"><label>专注分钟<input v-model.number="settingForm.focusMinutes" type="number" min="1" max="180"></label><label>短休分钟<input v-model.number="settingForm.shortBreakMinutes" type="number" min="1" max="60"></label><label>长休分钟<input v-model.number="settingForm.longBreakMinutes" type="number" min="1" max="120"></label><label>长休间隔<input v-model.number="settingForm.longBreakInterval" type="number" min="2" max="12"></label></div><div class="inline-actions"><Button @click="saveSettings">保存参数</Button></div></section>
    <section class="efficiency-panel"><h2>最近专注</h2><div v-if="!focus.sessions.length" class="empty-copy">还没有专注记录</div><ul v-else class="efficiency-list"><li v-for="session in focus.sessions" :key="session.publicId"><span><b>{{ session.taskTitle || '未关联任务' }}</b><small>{{ formatTime(session.startedAt) }} · {{ session.status === 'COMPLETED' ? '已完成' : '已放弃' }}</small></span><strong>{{ session.actualMinutes }} 分钟</strong></li></ul><p class="scope-note">专注时长不计入工时，也不参与工资或加班计算。</p></section>
  </main>
</template>
<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { Check, Settings2, Square, Timer } from 'lucide-vue-next'
import Button from '../components/ui/Button.vue'
import { useTaskFocusStore } from '../stores/taskFocus.js'
import { useTasksStore } from '../stores/tasks.js'
const route = useRoute(); const focus = useTaskFocusStore(); const tasksStore = useTasksStore(); const settingsOpen = ref(false); const selectedTask = ref(''); const requestedDate = ref(String(route.query.date || '')); const settingForm = reactive({ focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15, longBreakInterval: 4 })
watch(() => focus.settings, value => { if (value) Object.assign(settingForm, value) }, { immediate: true })
async function saveSettings() { await focus.saveSettings(settingForm); settingsOpen.value = false }
function formatTime(value) { return new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
onMounted(async () => { await tasksStore.init({ waitForRemote: false }); await focus.refresh() })
</script>
<style scoped>
.efficiency-page{max-width:980px;margin:0 auto;padding:34px 28px 100px}.efficiency-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px}.efficiency-head h1{margin:5px 0;font-size:2rem}.efficiency-head p:last-child{margin:0;color:var(--muted)}.focus-stage{display:grid;justify-items:center;gap:12px;margin:28px 0 18px;padding:52px 20px;border:1px solid var(--line);background:var(--panel2);text-align:center}.focus-stage.running{background:color-mix(in srgb,var(--accent-soft) 60%,var(--panel))}.focus-stage p,.focus-stage span{margin:0;color:var(--muted)}.focus-stage strong{font-size:clamp(4rem,12vw,8rem);font-variant-numeric:tabular-nums;line-height:1}.focus-actions,.inline-actions{display:flex;gap:8px}.focus-summary{display:grid;grid-template-columns:repeat(3,1fr) minmax(180px,1.4fr);gap:1px;margin-bottom:18px;background:var(--line);border:1px solid var(--line)}.focus-summary>div,.focus-summary>label{display:grid;gap:5px;padding:16px;background:var(--panel)}.focus-summary b{font-size:1.2rem}.focus-summary span,.focus-summary label{color:var(--muted);font-size:.75rem}.focus-summary select,.form-grid input{min-height:34px;margin-top:5px;padding:6px 8px;border:1px solid var(--line2);background:var(--card);color:var(--ink)}.efficiency-panel{margin-top:18px;padding:20px;border:1px solid var(--line);background:var(--panel)}.efficiency-panel h2{margin:0 0 16px;font-size:1rem}.form-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.form-grid label{display:grid;color:var(--muted);font-size:.75rem}.efficiency-list{list-style:none;margin:0;padding:0}.efficiency-list li{display:flex;justify-content:space-between;gap:12px;padding:13px 0;border-bottom:1px solid var(--line)}.efficiency-list small{display:block;margin-top:4px;color:var(--muted)}.scope-note,.empty-copy{color:var(--muted);font-size:.8rem}.efficiency-error{padding:10px;border-left:3px solid var(--down);background:color-mix(in srgb,var(--down) 8%,transparent)}@media(max-width:700px){.efficiency-page{padding:22px 14px 100px}.focus-summary{grid-template-columns:repeat(2,1fr)}.focus-summary>label{grid-column:1/-1}.form-grid{grid-template-columns:repeat(2,1fr)}}
</style>
