<template>
  <main class="efficiency-page"><header class="efficiency-head"><div><p class="label">TASKS / COUNTDOWNS</p><h1>倒数日</h1><p>纪念日和目标日期独立于任务状态。</p></div><Button @click="openForm()"><Plus :size="16" />新建倒数日</Button></header><p v-if="error" class="efficiency-error">{{ error }}</p><section class="countdown-grid"><article v-for="item in items" :key="item.publicId" class="countdown-card" :class="{ pinned:item.pinned }"><div class="countdown-head"><h2>{{ item.title }}</h2><div><button type="button" title="编辑" @click="openForm(item)"><Pencil :size="15" /></button><button type="button" title="删除" @click="remove(item)"><Trash2 :size="15" /></button></div></div><strong>{{ relative(item) }}</strong><p>{{ item.targetDate }} · {{ item.kind === 'ANNIVERSARY' ? '纪念日' : '倒数日' }}{{ item.repeatYearly ? ' · 每年重复' : '' }}</p><small>{{ item.note }}</small></article></section><Dialog v-model:open="formOpen" :title="editing ? '编辑倒数日' : '新建倒数日'"><form id="countdown-form" class="form-grid" @submit.prevent="save"><label>标题<input v-model="form.title" required maxlength="160"></label><label>目标日期<input v-model="form.targetDate" type="date" required></label><label>类型<select v-model="form.kind"><option value="COUNTDOWN">倒数日</option><option value="ANNIVERSARY">纪念日</option></select></label><label>颜色<input v-model="form.color" type="color"></label><label class="check-field"><input v-model="form.repeatYearly" type="checkbox">每年重复</label><label class="check-field"><input v-model="form.pinned" type="checkbox">置顶</label><label class="full-field">备注<textarea v-model="form.note" maxlength="1000"></textarea></label></form><template #footer><Button type="submit" form="countdown-form">保存</Button></template></Dialog></main>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { Pencil, Plus, Trash2 } from 'lucide-vue-next'
import Button from '../components/ui/Button.vue'
import Dialog from '../components/ui/Dialog.vue'
import { useTasksStore } from '../stores/tasks.js'
const store = useTasksStore(); const items = computed(() => [...store.countdowns].sort((a,b) => Number(b.pinned)-Number(a.pinned) || a.targetDate.localeCompare(b.targetDate))); const error = computed(() => store.error); const formOpen = ref(false); const editing = ref(null); const form = reactive({ title:'', targetDate:new Date().toISOString().slice(0,10), kind:'COUNTDOWN', repeatYearly:false, pinned:false, color:'#2f746f', note:'' })
function openForm(item = null) { editing.value = item; Object.assign(form, item ? { ...item } : { title:'', targetDate:new Date().toISOString().slice(0,10), kind:'COUNTDOWN', repeatYearly:false, pinned:false, color:'#2f746f', note:'' }); formOpen.value = true }
function relative(item) { const today = new Date(); today.setHours(0,0,0,0); let target = new Date(`${item.targetDate}T00:00:00`); if (item.repeatYearly) { target = new Date(today.getFullYear(), target.getMonth(), target.getDate()); if (target < today) target.setFullYear(target.getFullYear() + 1) } const days = Math.round((target - today) / 86400000); return days === 0 ? '就是今天' : days > 0 ? `还有 ${days} 天` : `已过 ${Math.abs(days)} 天` }
async function save() { const payload = { title:form.title, targetDate:form.targetDate, kind:form.kind, repeatYearly:form.repeatYearly, pinned:form.pinned, color:form.color, note:form.note }; if (editing.value) await store.updateCountdown(editing.value, payload); else await store.createCountdown(payload); formOpen.value = false }
async function remove(item) { if (!window.confirm(`删除倒数日“${item.title}”？`)) return; await store.deleteCountdown(item) }
onMounted(() => store.init({ waitForRemote:false }))
</script>
<style scoped>
.efficiency-page{max-width:980px;margin:0 auto;padding:34px 28px 100px}.efficiency-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px}.efficiency-head h1{margin:5px 0;font-size:2rem}.efficiency-head p:last-child{margin:0;color:var(--muted)}.efficiency-error{padding:10px;border-left:3px solid var(--down);background:color-mix(in srgb,var(--down) 8%,transparent)}.countdown-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:26px}.countdown-card{min-height:150px;padding:18px;border-left:3px solid var(--line2);border:1px solid var(--line);background:var(--panel)}.countdown-card.pinned{border-left-color:var(--accent)}.countdown-head{display:flex;justify-content:space-between;gap:8px}.countdown-head h2{margin:0;font-size:1rem}.countdown-head button{display:inline-grid;width:28px;height:28px;place-items:center;border:0;background:transparent;color:var(--muted)}.countdown-card>strong{display:block;margin:24px 0 4px;font-size:1.5rem}.countdown-card p,.countdown-card small{margin:0;color:var(--muted);font-size:.78rem}.countdown-card small{display:block;margin-top:10px}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.form-grid label{display:grid;gap:6px;color:var(--muted);font-size:.78rem}.form-grid input,.form-grid select,.form-grid textarea{min-height:38px;padding:7px 9px;border:1px solid var(--line2);background:var(--card);color:var(--ink)}.check-field{display:flex!important;align-items:center;gap:8px}.full-field{grid-column:1/-1}.full-field textarea{min-height:80px}@media(max-width:760px){.efficiency-page{padding:22px 14px 100px}.efficiency-head{align-items:flex-start;flex-direction:column}.countdown-grid{grid-template-columns:1fr}}
</style>
